name: firebase_utilitas
description: "A package streamlining Firebase tasks: Firestore CRUD operations, file uploads to Firebase Storage, and Firebase Auth functions including email sign-in, registration, password reset, and email verification"
version: 0.0.3
repository: https://github.com/Tomjerry12345/firebase_utilitas
license: MIT

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  path: ^1.8.3
  cloud_firestore: ^4.13.1
  firebase_auth: ^4.14.0
  firebase_storage: ^11.5.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

